# Homework 6 RF Accuracy Improvement

This assignment is inspired by examples of Shan-Hung Wu from National Tsing Hua University.

Requirement: improve the accuracy per feature of the following code from 0.03 up to at least 0.40 and accuracy should be more than 0.92

Here are three hints:

    You can improve the ratio by picking out or "creating" several features.
    Tune hyperparameters
    The ratio can be improved from 0.03 up to 0.47.

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

import numpy as np


# load the breast_cancer dataset
init_data = load_breast_cancer()

(X, y) = load_breast_cancer(return_X_y=True)

print(X)
print(np.max(X))
print(np.min(X))

# TODO Select some features (X), hint: based on the connections with
# our Y (importance? correlation?)
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y,
                                                random_state=0)

model = RandomForestClassifier()
model.fit(Xtrain, ytrain)
ypred = model.predict(Xtest)

print(model.get_params().keys())

# TODO need 5 fold cross validation

scores = cross_val_score(model, X, y, cv=5)
print(scores.mean())

# TODO Tune parameters for RandomForestClassifier
rng = np.random.randint(10, 200)

parameters = {'n_estimators':[rng], 'max_features':[1, 2]}

rfcTune = RandomizedSearchCV(model, parameters, cv = 10, n_iter=2)
rfcMod = rfcTune.fit(Xtrain, ytrain)
print(rfcMod.best_params_)

newModel = RandomForestClassifier(**rfcMod.best_params_)
newModel.fit(Xtrain, ytrain)
newYpred = model.predict(Xtest)

# TODO Calculate Average accuracy score

print("Accuracy:", metrics.accuracy_score(ytest, newYpred))

# TODO Calculate Average (accuracy score/number of features)

print("Average Accuracy:", metrics.accuracy_score(ytest, newYpred)/2)



[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
4254.0
0.0
dict_keys(['bootstrap', 'ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'max_samples', 'min_impurity_decrease', 'min_impurity_split', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'n_estimators', 'n_jobs', 'oob_score', 'random_state', 'verbose', 'warm_start'])
0.9631268436578171
{'n_estimators': 36, 'max_features': 1}
Accuracy: 0.965034965034965
Average Accuracy: 0.4825174825174825
